debug: false
uuid: 45411fda-4abc-44f5-91c3-e029f6db819e
token_id: pzx9rrRoKSBNft46
token: HX0PzyqCK0ks1gxE4oo6mt7KBpxBpjt7NJxLyMw3fqQgWtPG8ThPaajydkvFEI13
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/192.168.205.1/fullchain.pem
    key: /etc/letsencrypt/live/192.168.205.1/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://192.168.1.109'
